apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app-1
  namespace: nginx-test-app
spec:
  interval: 1m
  path: "./repositories/app-1/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app-1